version: '3.3'

services:
  mysql:
    image: mysql:5.7
    container_name: topic-voting-mysql
    restart: always
    environment:
      MYSQL_DATABASE: topic-voting
      MYSQL_USER: master
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root
      TZ: UTC
    ports:
      - '3306:3306'
    user: 1000:1000
    volumes:
      - ./docker/mysql/conf/custom.cnf:/etc/mysql/conf.d/custom.cnf
      - ./data/mysql:/var/lib/mysql:rw
    networks:
        - backend

volumes:
    mysql:
        driver: local

networks:
  backend:
    driver: bridge
